package com.tcptun.client.ui.theme

import androidx.compose.ui.graphics.Color

// Calm Material 3 palette — soft blue primary, neutral surfaces.

val PrimaryLight = Color(0xFF3B6A9A)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFD3E4FF)
val OnPrimaryContainerLight = Color(0xFF001C38)
val SecondaryLight = Color(0xFF545F70)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFD8E3F8)
val OnSecondaryContainerLight = Color(0xFF111C2B)
val TertiaryLight = Color(0xFF3D6A4A)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFBEF0C8)
val OnTertiaryContainerLight = Color(0xFF00210F)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val BackgroundLight = Color(0xFFF8F9FC)
val OnBackgroundLight = Color(0xFF191C20)
val SurfaceLight = Color(0xFFF8F9FC)
val OnSurfaceLight = Color(0xFF191C20)
val SurfaceVariantLight = Color(0xFFDFE2EB)
val OnSurfaceVariantLight = Color(0xFF43474E)
val OutlineLight = Color(0xFF73777F)
val OutlineVariantLight = Color(0xFFC3C6CF)
val SurfaceDimLight = Color(0xFFD9DADE)
val SurfaceBrightLight = Color(0xFFF8F9FC)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF2F3F7)
val SurfaceContainerLight = Color(0xFFECEEF2)
val SurfaceContainerHighLight = Color(0xFFE6E8EC)
val SurfaceContainerHighestLight = Color(0xFFE1E2E6)

val PrimaryDark = Color(0xFFA3C9FF)
val OnPrimaryDark = Color(0xFF00315C)
val PrimaryContainerDark = Color(0xFF205081)
val OnPrimaryContainerDark = Color(0xFFD3E4FF)
val SecondaryDark = Color(0xFFBCC7DB)
val OnSecondaryDark = Color(0xFF263141)
val SecondaryContainerDark = Color(0xFF3C4758)
val OnSecondaryContainerDark = Color(0xFFD8E3F8)
val TertiaryDark = Color(0xFFA2D4AD)
val OnTertiaryDark = Color(0xFF0B381F)
val TertiaryContainerDark = Color(0xFF255134)
val OnTertiaryContainerDark = Color(0xFFBEF0C8)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val BackgroundDark = Color(0xFF111316)
val OnBackgroundDark = Color(0xFFE2E2E6)
val SurfaceDark = Color(0xFF111316)
val OnSurfaceDark = Color(0xFFE2E2E6)
val SurfaceVariantDark = Color(0xFF43474E)
val OnSurfaceVariantDark = Color(0xFFC3C6CF)
val OutlineDark = Color(0xFF8D9199)
val OutlineVariantDark = Color(0xFF43474E)
val SurfaceDimDark = Color(0xFF111316)
val SurfaceBrightDark = Color(0xFF37393C)
val SurfaceContainerLowestDark = Color(0xFF0C0E11)
val SurfaceContainerLowDark = Color(0xFF191C20)
val SurfaceContainerDark = Color(0xFF1D2024)
val SurfaceContainerHighDark = Color(0xFF282A2E)
val SurfaceContainerHighestDark = Color(0xFF333539)
